type: object
properties:
  id:
    type: string
    format: uuid
    description: Unique identifier representing a specific product.
  name:
    type: string
    description: Name of the product
  description:
    type: string
  dimensions:
    $ref: dimension.yaml
  categories:
    type: array
    items:
      $ref: category.yaml
  images:
    type: array
    items:
      $ref: image.yaml
  prices:
    type: string
    pattern: ^-?(?:0|[1-9]\d{0,2}(?:,?\d{3})*)(?:\.\d+)?$
  cost:
    type: string
    pattern: ^-?(?:0|[1-9]\d{0,2}(?:,?\d{3})*)(?:\.\d+)?$
  dateCreated:
    type: string
    format: date-time
  dateUpdated:
    type: string
    format: date-time
